/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import com.google.gson.Gson;


import java.io.*;

class AppTest {


    @Test void testReadFromFile() throws IOException {

        Gson gson = new Gson();
        File file = new File("src/test/resources/recentquotes.json");
        FileReader reader = new FileReader(file);
        Quotes[] fileString = gson.fromJson(reader, Quotes[].class);
        int arrayLength = fileString.length;
        int random = (int)(Math.random() * arrayLength);
        assertNotNull(fileString[random]);
    }
}
