/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.gson.Gson;


import java.io.*;


public class App {

    public static void getFromJson() throws FileNotFoundException{
        Gson gson = new Gson();
        File file = new File("app/src//main/resources/recentquotes.json");
        FileReader reader = new FileReader(file);
        Quotes[] fileString = gson.fromJson(reader, Quotes[].class);
        int arrayLength = fileString.length;
        int random = (int)(Math.random() * arrayLength);
        System.out.println(fileString[random]);
    }
    public static void main(String[] args) throws FileNotFoundException {
        getFromJson();
    }
}
